// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dispatch-full-desk/FullDesk.tsx": () => import("../components/mockups/dispatch-full-desk/FullDesk.tsx"),
  "./components/mockups/dispatch-home/UpgradedHome.tsx": () => import("../components/mockups/dispatch-home/UpgradedHome.tsx")
};
